routes/web.php
<?php

use App\Models\Showroom;
use App\Models\Setting;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('honda-dream', function () {
    return view('dreams',[
        'dreams' => Showroom::customDream(),
        'settings' => Setting::customFetchAll()
    ]);
});

Route::get('{page?}/{slug?}', function () {
    return view('index');
});

app/Models/Version.php
<?php

namespace App\Models;

class Version extends AppDescomplicarModel
{
	protected $table = 'versions';
	
    public function optionals()
	{
	    return $this->belongsToMany('App\Models\Optional', 'versions_has_optionals', 'versions_id', 'optionals_id');
	}

    public function colors()
	{
		return $this->hasMany('App\Models\Color', 'versions_id', 'id');
	}

	public function model()
	{
		return $this->belongsTo('App\Models\Model', 'models_id', 'id');
	}
	
	public function body()
	{
		return $this->belongsTo('App\Models\Body', 'bodies_id', 'id');
	}
	
	public function cc()
	{
		return $this->belongsTo('App\Models\Cc', 'cc_id', 'id');
	}
	
	public function motorization()
	{
		return $this->belongsTo('App\Models\Motorization', 'motorization_id', 'id');
	}
	
	public function transmission()
	{
		return $this->belongsTo('App\Models\Transmission', 'transmissions_id', 'id');
	}
	
	public function fuel()
	{
		return $this->belongsTo('App\Models\Fuel', 'fuels_id', 'id');
	}

	public function getCompleteNameAttribute($value)
	{
		$value = explode(" ", $value);
		foreach($value as $k => $v) {
			$v = strtolower($v);

			switch($v) {
				case "manual":
				case "sedan":
				case "hatch":
					unset($value[$k]);
					break;

				case "automatico":
				case "automático":
				case "automatizado":
					$value[$k] = 'AT';
					break;
			}
		}

		$value = trim(implode(" ", $value));

		return $value;
	}

}

resources/views/dreams.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Guanabara Motos - Honda Dream</title>
    
    <meta property="og:url" content="@yield('PAGE_URL', request()->fullUrl())">
    <meta property="og:type" content="{{ env('OG_TYPE', 'website') }}">
    <meta property="og:title" content="{{ @$settings['meta_title'] }}">
    <meta property="og:image" content="@yield('PAGE_IMAGE')">
    <meta property="og:description" content="{{ $settings['meta_description'] }}">
    <meta property="og:site_name" content="{{ @$settings['meta_title'] }}">
    <meta property="og:locale" content="pt_BR">
    <meta itemprop="name" content="{{ @$settings['meta_title'] }}">
    <meta itemprop="description" content="{{ $settings['meta_description'] }}">
    <meta itemprop="image" content="@yield('PAGE_IMAGE')">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@yield('TWITTER_ACCOUNT', env('TWITTER_ACCOUNT'))">
    <meta name="twitter:url" content="@yield('PAGE_URL', request()->fullUrl())">
    <meta name="twitter:title" content="{{ @$settings['meta_title'] }}">
    <meta name="twitter:description" content="{{ $settings['meta_description'] }}">
    <meta name="twitter:image" content="@yield('PAGE_IMAGE')">

    <link rel="stylesheet" href="{{ asset('css/dream.css') }}">
</head>
<body>
    <header class="header mb-2">
        <div class="container pb-5">
            <div class="row d-flex justify-content-center p-5">
                <img src="{{ asset('images/logo.png') }}" class="logo" alt="{{ env('APP_NAME') }}">
            </div>
            <div class="row">
                <h1 class="text-uppercase">escolha a <strong>honda que <br> combina com você!</strong></h1>
            </div>
            <div class="row d-flex justify-content-center pb-5">
                <a href="#dream" class="link">
                    <img src="{{ asset('images/icons/mouse.svg') }}" class="mouse d-none d-lg-block" alt="mouse">
                    <img src="{{ asset('images/icons/set-mouse.svg') }}" class="mouse-set d-none d-lg-block position-absolute" alt="mouse">
                    <img src="{{ asset('images/icons/mouse-mobile.svg') }}" class="mouse-set d-lg-none" alt="mouse">
                </a>
            </div>
        </div>
    </header>

    <section id="dream">
        <div id="offers" class="owl-carousel owl-theme">
            @foreach ($dreams as $item)
                <div class="item" style="background-image: linear-gradient(#0000009e, #0000009e), url({{ $item->banner_dream }})">
                    <div class="container">
                        <h1 class="pb-5 d-flex align-items-center">{{ $item->model->complete_name }}</h1>
                        <a onclick="javascript:location.href='showroom/{{ $item->model->slug }}'" class="btn btn-danger text-uppercase">
                            eu quero
                        </a>
                    </div>
                </div>
            @endforeach
        </div>
    </section>
    </section>

    <footer class="pt-5 pb-0 mb-0 footer">
        <div class="container-fluid">
            <h3 class="text-center text-uppercase pb-5">
                <strong>outros modelos</strong>
            </h3>
            <div class="row d-lg-none">
                <div id="offers-mobile" class="owl-carousel owl-theme">
                    @foreach ($dreams as $key => $item)
                        <a href="#dream" class="link" data-slide-to="{{ $key }}">
                            <div class="item" style="background-image: url({{ $item->banner_dream }})">
                                <div class="container d-flex justify-content-center align-items-center p-5">
                                    <h1>{{ $item->model->complete_name }}</h1>
                                </div>
                            </div>
                        </a>
                    @endforeach
                </div>
            </div>
            <div class="d-none d-lg-block">
                <div class="row">
                    @foreach ($dreams as $key => $item)
                        <div class="col-md-4 pb-5">     
                            <a href="#dream" class="link" data-slide-to="{{ $key }}">                       
                                <div class="item" style="background-image: url({{ $item->banner_dream }})">
                                    <div class="container d-flex justify-content-center align-items-center p-5">
                                        <h1>{{ $item->model->complete_name }}</h1>                                        
                                    </div>                                
                                </div>
                            </a>                         
                        </div>
                    @endforeach
                </div>
            </div>
            <div class="row pb-5">
                <div class="col-12 col-md-6">
                    <img src="{{ asset('images/logo.png') }}" width="200px" alt="{{ env('APP_NAME') }}">
                </div>
                <div class="col-12 col-md-6 text-right">
                    <p class="pt-2">Desenvolvido por <strong><a href="https://novam3.com.br">Nova M3</a> </strong></p>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $("#offers").owlCarousel({
                loop: true,
                margin: 10,
                nav: false,
                items: 1,
                dots: false,
                autoplay:true,
                autoplayTimeout:5000,
            });

            $("#offers-mobile").owlCarousel({
                loop: true,
                margin: 10,
                nav: false,
                items: 1,
                autoplay:true,
                autoplayTimeout:3000,
                dots: false,
                responsiveClass:true,
                responsive:{
                    768:{
                        items:3,
                    }
                }
            });

            $('.footer .link, #offers').bind('click', function(e){
                e.preventDefault();
                if($(this).hasClass('prev')){
                    $('#offers').trigger('prev.owl');
                }else if($(this).hasClass('next')){
                    $('#offers').trigger('next.owl');
                }else{
                    let slideTo = $(this).data('slide-to');
                    $('#offers').trigger('to.owl.carousel', slideTo);
                }
            });

            $('.link').on('click', ()=>{
                $('html, body').animate({
                    scrollTop: $('#dream').offset().top
                }, 500);
            })
        }) 
    </script>
</body>
</html>

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-N2GGC2N4Z5"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-N2GGC2N4Z5');
    </script>


    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="Guanabara Moto - Concessionária Honda" />
    <meta name="keywords"
        content=" cg 160, nxr 160 bros, pop 110i, biz 110i, biz 125, cg cargo, cg 125, fan, cg 160 start, titan, pcx, twister, bros, xre, pernambuco, concessionária honda, honda" />
    <meta name="facebook-domain-verification" content="yvy5wgqcupnjg7ny5eabfbi7rexxcw" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Guanabara Moto - Concessionária Honda" />
    <meta property="og:description" content="Guanabara Moto - Concessionária Honda" />
    <meta property="og:url" content="www.guanabaramotos.com.br" />
    <meta property="og:site_name" content="Guanabara Moto - Concessionária Honda" />
    <meta property="og:image" content="" />
    <meta property="og:locale" content="pt_BR" />

    <title>Guanabara Motos - Concessionária Honda</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>

<body>
    <div id="root"></div>
    <script type="text/javascript" src="{{ asset('js/index.js') }}"></script>
    {{-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous">
    </script> --}}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

    <script type="text/javascript">
        var GVP_AccountKey = "TvJL06on0oqb/TLTUSk9fiJtmpyRJT/y_TbjU/fVaSQQ=_HyH2GxthMls=",
            GVP_LoadStart = new Date();
        (function() {
            var s1 = document.createElement("script"),
                s2 = document.createElement("script"),
                s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = "https://app.dialugo.com/embed/monitoramento.js";
            s1.charset = "UTF-8";
            s2.src = "https://embed.dialugo.com/jquery.min.js";
            s0.parentNode.insertBefore(s2, s0);
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
</body>

</html>